---
title: "NYC Portfolio"
output: html_notebook
---

# Electric   

```{r, echo=FALSE, results="hide", include=FALSE}
  # Enviroment 
  # Loading and preprocessing the data
  #Set up enviroment for R scrip  
  # Packages for tidyverse 
    library("tidyverse")
    library("lubridate")
  # Package for building tables in markdown and notebook 
    library("knitr")
    library("kableExtra") 
    library("xtable")
  # Package for forecasting
    library("fpp2")
  # Packages for reading excel and html files and XML
    library("openxlsx")
    library("XML")
  # Parkage for using data tables for very large data operations
    library("data.table")
  #Package for reading fixed width tables
    library("utils")
  # Packages for reading data through API's 
    library("httr")
    library("jsonlite")
  # Package for performing inquires with SQL databases 
    library("sqldf")
  #Package for reading and writing to jpeg files
    library("jpeg")

  # Set proper working Dir 
    if (!getwd() == "C:/Users/paulr/Documents/RXR_Energy") {setwd("C:/Users/paulr/Documents/RXR_Energy")}

# Set proper working Dir
if (!getwd() == "C:/Users/paulr/Documents/RXR_Energy") {setwd("./RXR_Energy")}

# Check for data directory and if one is not present then make it
if (!file.exists("data")) {
  dir.create("data")
}

```

# Data from utility bills 

```{r, echo=FALSE}
#Read in data and fix formats

alldata <- read_csv("./data/MASTER METERING DATA(2).csv", col_names = TRUE, col_types = "cccccddcd")
alldata$`Start Date`<- mdy(alldata$`Start Date`)
alldata$`End Date` <- mdy(alldata$`End Date`)
glimpse(alldata)
str(alldata)
head(alldata)
tail(alldata)


# Bring in DD and then join days per month to get a dataframe with DD/day to then combine with the main alldata

hdd <- read_csv("./data/NYSERDA HDD.csv")
colnames(hdd)[1] <- "Month"
cdd <- read_csv("./data/NYSERDA CDD.csv")
colnames(cdd)[1] <- "Month"
month_days <- data.frame(Month = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"), days = c(31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31))





```




```{r, echo=FALSE}
#Summerarise by building, and fuel type and year.
alldata %>% mutate(year(`Start Date`)) %>% group_by(Building, `Meter Type`, Year, Units) %>%
  summarise(Consumpton = sum(Usage)) %>% select(Building, `Meter Type`, Year, Consumpton, Units) -> annualdata
annualdata %>% ggplot(aes(Year,Consumpton))+ geom_line() + facet_grid(~Building)

glimpse(annualdata)


# Add comsumption per day 
alldata %>% mutate("day_per_month" = as.numeric(difftime(alldata$`End Date`,alldata$`Start Date`, units = "days")), Cosum_per_day = as.numeric(Usage/day_per_month), "Month" = month(alldata$`End Date`)) %>% mutate( period = ymd(paste(year(alldata1$`End Date`[2]), month(alldata1$`End Date`[2]), 1, sep='-'))) -> alldata1
head(alldata1)
glimpse(alldata1)

alldata1 %>% filter(Building == "WWP" & `Meter Type` == "Electric")  %>% ggplot(aes(Month, y = Usage, ))+geom_col() 

alldata1 %>% filter(Year == 2019) %>% group_by(Building, `Meter Type`,Year, Month) %>% summarise(Consumption = sum(Usage)) %>% ggplot(aes(Month ,Consumption/1000)) + geom_col() + facet_wrap(~Building)









```

#Baseload Electric Tabulation
```{r, echo=FALSE}




```



